package core

const (
	INFO    = "info"
	DEBUG   = "debug"
	WARNING = "warning"
	ERROR   = "error"
	FATAL   = "fatal"
)

const (
	DEFAULT_TIMESTAMP_FORMAT = "DAY of MONTH YEAR | HOUR:MINUTE:SECOND AM/PM"
	SHORT_TIMESTAMP_FORMAT   = "DAY/MONTH/YEAR | HOUR:MINUTE"
	MID_TIMESTAMP_FORMAT     = "DAY MONTH YEAR | HOUR:MINUTE:SECOND"
	LONG_TIMESTAMP_FORMAT    = "DAY of MONTH YEAR | HOUR:MINUTE:SECOND AM/PM"
)

const (
	DAY        = "DAY"
	MONTH      = "MONTH"
	YEAR       = "YEAR"
	TIME_SHORT = "HOUR:MINUTE"
	TIME_LONG  = "HOUR:MINUTE:SECOND"
	AM_PM      = "AM/PM"
	TIME_AM_PM = "HOUR:MINUTE:SECOND AM/PM"
)
